language: csharp
solution: cloudscribe.Web.Navigation.sln
sudo: false
dist: trusty
mono: 5.0.1
dotnet: 1.0.4
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux
  - osx
osx_image: xcode8.3
script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release
  - dotnet test -c Release ./test/cloudscribe.Web.Navigation.Test/cloudscribe.Web.Navigation.Test.csproj